name: repeathmmenv
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - htslib=1.9
  - biopython=1.66=np112py27_0
  - blas=1.0=mkl
  - bwa=0.7.17=hed695b0_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py27_0
  - curl=7.61
  - freetype=2.10.2=he06d7ca_0
  - hmmlearn=0.2.1=py27h3010b51_1000
  - intel-openmp=2020.1=217
  - jpeg=9d=h516909a_0
  - krb5=1.16
  - libcurl=7.61
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.8
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_6
  - libwebp-base=1.1.0=h516909a_3
  - lz4-c=1.9.2=he1b5a44_1
  - make=4.2.1=h1bed415_1
  - mkl=2018.0.3=1
  - mmtf-python=1.1.2=py_0
  - msgpack-python=1.0.0=py27h9e3301b_1
  - ncurses=6.2=he6710b0_1
  - numpy=1.12.1=py27h9378851_1
  - olefile=0.46=py_0
  - openssl=1.0
  - pcre=8.43=he6710b0_0
  - peakutils=1.1.0=py27_0
  - perl=5.26.2=h14c3975_0
  - pillow=5.3.0=py27h00a061d_1000
  - pip=19.3.1=py27_0
  - python=2.7.18=h15b4118_1
  - python_abi=2.7=1_cp27mu
  - readline=8.0=h7b6447c_0
  - reportlab=3.5.42=py27heca39a3_0
  - samtools=1.7=1
  - scikit-learn=0.19.2=py27h4989274_0
  - scipy=1.1.0=py27hd20e5f9_0
  - setuptools=44.0.0=py27_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - swig=3.0.12=h38cdd7d_3
  - tk=8.6.8=hbc83047_0
  - trf=4.09=2
  - wheel=0.33.6=py27_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h6597ccf_3

